# Generated by Django 3.1.6 on 2021-02-19 01:23

from django.db import migrations, models
import questionary.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headQuestion', models.CharField(max_length=500, verbose_name='Head Question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('idQuestionary', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Text name')),
                ('questions', models.ManyToManyField(related_name='questionnaires', to='questionary.Question', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'Questionary',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('idChoice', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textChoice', models.TextField(max_length=200, verbose_name='Text Choice')),
                ('score', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=questionary.models.Question, related_name='choices', to='questionary.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
